AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SimpleAwsBucket:
    Type: AWS::S3::Bucket
  cloudfrontoriginaccessidentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: cff-OAI
  CffBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
     Bucket: !Ref SimpleAwsBucket
     PolicyDocument:
      Statement:
        - Action:
            - 's3:GetObject'
          Effect: Allow
          Resource: !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref SimpleAwsBucket
              - /*
          Principal: 
            CanonicalUser: !GetAtt cloudfrontoriginaccessidentity.S3CanonicalUserId
  SimpleAWSDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: "Simple AWS LambdaAtEdge Redirect"
        Origins:
        - DomainName: !GetAtt SimpleAwsBucket.DomainName
          Id: simpleAWSS3Origin
          S3OriginConfig:
            OriginAccessIdentity: !Join ['', ['origin-access-identity/cloudfront/', !Ref cloudfrontoriginaccessidentity]]
        Enabled: 'true'
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          TargetOriginId: simpleAWSS3Origin
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_100
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: simple-aws-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - edgelambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: logaccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*