AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template for a simple VPC, Subnet, Security Group, EC2 instance and SSM setup.

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-arm64'

Resources:
  SimpleAWSVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: SimpleAWSVPC

  SimpleAWSSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref SimpleAWSVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: SimpleAWSSubnet

  SimpleAWSInternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: SimpleAWSInternetGateway

  SimpleAWSVPCGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref SimpleAWSVPC
      InternetGatewayId: !Ref SimpleAWSInternetGateway

  SimpleAWSRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref SimpleAWSVPC
      Tags:
        - Key: Name
          Value: SimpleAWSRouteTable

  SimpleAWSRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: SimpleAWSVPCGatewayAttachment
    Properties:
      RouteTableId: !Ref SimpleAWSRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref SimpleAWSInternetGateway

  SimpleAWSSubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref SimpleAWSSubnet
      RouteTableId: !Ref SimpleAWSRouteTable

  SimpleAWSSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security Group for EC2 instances
      VpcId: !Ref SimpleAWSVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SimpleAWSSecurityGroup

  SimpleAWSEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref LatestAmiId
      SubnetId: !Ref SimpleAWSSubnet
      InstanceType: t4g.small
      SecurityGroupIds:
        - !Ref SimpleAWSSecurityGroup